# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"#\n\x0b\x43hatRequest\x12\x14\n\x0cuser_message\x18\x01 \x01(\t\"$\n\x0c\x43hatResponse\x12\x14\n\x0c\x62ot_response\x18\x01 \x01(\t25\n\x0e\x42\x61nkingChatbot\x12#\n\x04\x43hat\x12\x0c.ChatRequest\x1a\r.ChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=14
  _globals['_CHATREQUEST']._serialized_end=49
  _globals['_CHATRESPONSE']._serialized_start=51
  _globals['_CHATRESPONSE']._serialized_end=87
  _globals['_BANKINGCHATBOT']._serialized_start=89
  _globals['_BANKINGCHATBOT']._serialized_end=142
# @@protoc_insertion_point(module_scope)
